#!/usr/bin/env python3
"""
Generates embeddings for products.csv and writes seed.sql for Docker.

Run once before the session:
    python -m venv .venv && source .venv/bin/activate
    pip install sentence-transformers
    python generate_embeddings.py

Output: seed.sql (INSERT statements with pre-computed 384-dim vectors)

Model: all-MiniLM-L6-v2 — ~80 MB download, runs on CPU in seconds.
Dimension: 384 (matches schema.sql's vector(384)).
"""

import csv
import sys
from pathlib import Path

try:
    from sentence_transformers import SentenceTransformer
except ImportError:
    sys.exit("pip install sentence-transformers first")

HERE = Path(__file__).parent
CSV_PATH = HERE / "products.csv"
OUT_PATH = HERE / "seed.sql"
MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


def vec_literal(values):
    return "[" + ",".join(f"{v:.6f}" for v in values) + "]"


def main():
    print(f"loading model {MODEL_NAME} (first run downloads ~80 MB)…")
    model = SentenceTransformer(MODEL_NAME)

    with CSV_PATH.open() as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    print(f"encoding {len(rows)} product descriptions…")
    descriptions = [r["description"] for r in rows]
    vectors = model.encode(descriptions, show_progress_bar=True, normalize_embeddings=True)

    print(f"writing {OUT_PATH}…")
    with OUT_PATH.open("w") as out:
        out.write("-- Auto-generated by generate_embeddings.py. Do not hand-edit.\n")
        out.write("-- Regenerate if you change products.csv.\n\n")
        out.write("BEGIN;\n\n")

        for row, vec in zip(rows, vectors):
            vec_sql = vec_literal(vec)
            desc = row["description"].replace("'", "''")
            loc = row["store_location"].replace("'", "''")
            out.write(
                "INSERT INTO cymbal_products "
                "(product_id, description, price, store_location, embedding) VALUES ("
                f"'{row['product_id']}', '{desc}', {row['price']}, '{loc}', '{vec_sql}');\n"
            )
        out.write("\n-- Mirror into the no-index table so the index-comparison demo works:\n")
        out.write(
            "INSERT INTO cymbal_products_noindex "
            "SELECT * FROM cymbal_products;\n"
        )
        out.write("\nCOMMIT;\n")

    print(f"done. {len(rows)} rows written to seed.sql")
    print("now run:  docker compose up -d")


if __name__ == "__main__":
    main()
